site_name: Skillbase
nav:
  - 'Home': 'index.md'
  - 'Backend':
    - 'Overview': 'backend/index.md'
    - 'Design': 'backend/design.md'
    - 'Build': 'backend/build.md'
    - 'Test': 'backend/test.md'
    - 'Services':
      - 'Catalog':
        - 'Overview': 'backend/catalog/index.md'
        - 'Design': 'backend/catalog/design.md'
        - 'Build': 'backend/catalog/build.md'
        - 'Test': 'backend/catalog/test.md'
        - 'Endpoints': 'backend/catalog/endpoints.md'
      - 'Workflow':
        - 'Overview': 'backend/workflow/index.md'
        - 'Design': 'backend/workflow/design.md'
        - 'Build': 'backend/workflow/build.md'
        - 'Test': 'backend/workflow/test.md'
        - 'Endpoints': 'backend/workflow/endpoints.md'
      - 'Member':
        - 'Overview': 'backend/member/index.md'
        - 'Design': 'backend/member/design.md'
        - 'Build': 'backend/member/build.md'
        - 'Test': 'backend/member/test.md'
        - 'Endpoints': 'backend/member/endpoints.md'
  - 'Frontend':
      - 'Overview': 'frontend/index.md'
      - 'Design': 'frontend/design.md'
      - 'Build': 'frontend/build.md'
      - 'Test': 'frontend/test.md'
  - 'System':
    - 'Overview': 'system/index.md'
    - 'Design': 'system/design.md'
    - 'Build': 'system/build.md'
    - 'Test': 'system/test.md'

theme: readthedocs

